### PR TITLE
Update mrml to 4.0.1

### PR DESCRIPTION
**Pull request by ushi-as**
Hi @jonian 

My team is looking forward to a bugfix in mrml 4.0.1. Is it possible to release a gem with the new version?

Cheers, ushi

### CODE REVIEW

**Comment by jonian** [comment]
Hey @ushi-as, this is not building, the api has changed in mrml v4.

**Comment by ushi-as** [comment]
@jonian I see. I will look into it.

**Comment by ushi-as** [comment]
@jonian it should build now.

**Comment by jonian** [comment]
Yes, it builds successfully and the tests pass. Thank you for your contribution @ushi-as!

**Comment by ushi-as** [comment]
@jonian do you have any plans on releasing it yet?

**Comment by ushi-as** [comment]
@jonian That would be awesome. Thank you very much.

**Pull request merged**
